<?php
declare(strict_types=1);
namespace StageArtPlugIn\Domain\Ticket;
final class TicketRepository{
 private \wpdb $db;private string $r;private string $c;private string $l;
 public function __construct(?\wpdb $db=null){global $wpdb;$this->db=$db??$wpdb;$p=$this->db->prefix;$this->r=$p.'stageart_plugin_ticket_reservations';$this->c=$p.'stageart_plugin_ticket_checkins';$this->l=$p.'stageart_plugin_ticket_sales_links';}
 public function reservations(int $performanceId):array{return $this->db->get_results($this->db->prepare("SELECT r.*,c.id AS checkin_id,c.checked_in_at FROM {$this->r} r LEFT JOIN {$this->c} c ON c.reservation_id=r.id WHERE r.performance_id=%d AND r.status='confirmed' ORDER BY r.created_at,r.id",$performanceId),ARRAY_A)?:[];}
 public function reservedQuantity(int $performanceId):int{return (int)$this->db->get_var($this->db->prepare("SELECT COALESCE(SUM(quantity),0) FROM {$this->r} WHERE performance_id=%d AND status='confirmed'",$performanceId));}
 public function findReservation(int $id):?array{$x=$this->db->get_row($this->db->prepare("SELECT r.*,c.id AS checkin_id,c.checked_in_at FROM {$this->r} r LEFT JOIN {$this->c} c ON c.reservation_id=r.id WHERE r.id=%d",$id),ARRAY_A);return $x?:null;}
 public function findSalesLink(int $productionId,string $slug):?array{$x=$this->db->get_row($this->db->prepare("SELECT * FROM {$this->l} WHERE production_id=%d AND slug=%s AND status='publish' LIMIT 1",$productionId,$slug),ARRAY_A);return $x?:null;}
 public function salesLinks(int $productionId):array{return $this->db->get_results($this->db->prepare("SELECT * FROM {$this->l} WHERE production_id=%d ORDER BY id",$productionId),ARRAY_A)?:[];}
 public function saveSalesLink(int $productionId,int $userId,string $slug):int{$now=gmdate('Y-m-d H:i:s');$existing=$this->findSalesLinkByUser($productionId,$userId);$data=['production_id'=>$productionId,'authcore_user_id'=>$userId,'slug'=>sanitize_title($slug),'status'=>'publish','updated_at'=>$now];if($existing){$this->db->update($this->l,$data,['id'=>(int)$existing['id']],['%d','%d','%s','%s','%s'],['%d']);return (int)$existing['id'];}$data['created_at']=$now;$this->db->insert($this->l,$data,['%d','%d','%s','%s','%s','%s']);return (int)$this->db->insert_id;}
 private function findSalesLinkByUser(int $productionId,int $userId):?array{$x=$this->db->get_row($this->db->prepare("SELECT * FROM {$this->l} WHERE production_id=%d AND authcore_user_id=%d LIMIT 1",$productionId,$userId),ARRAY_A);return $x?:null;}
 public function createReservation(array $data):int{$now=gmdate('Y-m-d H:i:s');$this->db->insert($this->r,['reservation_no'=>$data['reservation_no'],'production_id'=>(int)$data['production_id'],'performance_id'=>(int)$data['performance_id'],'customer_name'=>$data['customer_name'],'customer_name_kana'=>$data['customer_name_kana'],'customer_email'=>$data['customer_email'],'quantity'=>(int)$data['quantity'],'authcore_user_id'=>!empty($data['authcore_user_id'])?(int)$data['authcore_user_id']:null,'source'=>$data['source']??'online','status'=>'confirmed','created_at'=>$now,'updated_at'=>$now],['%s','%d','%d','%s','%s','%s','%d','%d','%s','%s','%s','%s']);return (int)$this->db->insert_id;}
 public function checkIn(int $reservationId,?int $by=null):bool{$x=$this->findReservation($reservationId);if(!$x||!empty($x['checkin_id']))return false;$now=gmdate('Y-m-d H:i:s');return false!==$this->db->insert($this->c,['reservation_id'=>$reservationId,'checked_in_at'=>$now,'checked_in_by'=>$by,'created_at'=>$now],['%d','%s','%d','%s']);}
 public function checkInCount(int $performanceId):int{return (int)$this->db->get_var($this->db->prepare("SELECT COALESCE(SUM(r.quantity),0) FROM {$this->r} r INNER JOIN {$this->c} c ON c.reservation_id=r.id WHERE r.performance_id=%d AND r.status='confirmed'",$performanceId));}
 public function nextReservationNo(string $prefix):string{$date=wp_date('Ymd',current_time('timestamp',true));$like=$prefix.'-'.$date.'-%';$n=(int)$this->db->get_var($this->db->prepare("SELECT COUNT(*) FROM {$this->r} WHERE reservation_no LIKE %s",$like));return sprintf('%s-%s-%04d',$prefix,$date,$n+1);}
}
