<?php

declare(strict_types=1);

namespace StageArtPlugIn\Domain\Member;

final class MemberRepository
{
    public const ROLES = ['actor'=>'俳優','director'=>'演出','writer'=>'脚本','production'=>'制作','sound'=>'音響','lighting'=>'照明','stage_manager'=>'舞台監督','representative'=>'劇団代表'];
    public const SOCIAL_PLATFORMS = ['x'=>'X','instagram'=>'Instagram','facebook'=>'Facebook','youtube'=>'YouTube','tiktok'=>'TikTok'];
    public function all(bool $publicOnly=false):array{global $wpdb;$t=$wpdb->prefix.'stageart_plugin_members';$w=$publicOnly?"WHERE status='published'":'';return $wpdb->get_results("SELECT * FROM {$t} {$w} ORDER BY display_order ASC,id ASC",ARRAY_A)?:[];}
    public function find(int $id):?array{global $wpdb;$t=$wpdb->prefix.'stageart_plugin_members';$r=$wpdb->get_row($wpdb->prepare("SELECT * FROM {$t} WHERE id=%d",$id),ARRAY_A);if(!$r)return null;$r['roles']=$this->roles($id);$r['social']=$this->social($id);$r['custom_fields']=$this->customValues($id);return $r;}
    public function findBySlug(string $slug):?array{global $wpdb;$t=$wpdb->prefix.'stageart_plugin_members';$id=(int)$wpdb->get_var($wpdb->prepare("SELECT id FROM {$t} WHERE slug=%s",$slug));return $id?$this->find($id):null;}
    public function findBySlugHistory(string $slug):?array{global $wpdb;$h=$wpdb->prefix.'stageart_plugin_member_slug_history';$id=(int)$wpdb->get_var($wpdb->prepare("SELECT member_id FROM {$h} WHERE slug=%s",$slug));return $id?$this->find($id):null;}
    public function currentSlug(int $id):?string{global $wpdb;$t=$wpdb->prefix.'stageart_plugin_members';$slug=$wpdb->get_var($wpdb->prepare("SELECT slug FROM {$t} WHERE id=%d",$id));return $slug!==null?(string)$slug:null;}
    public function save(array $d):int{global $wpdb;$t=$wpdb->prefix.'stageart_plugin_members';$now=current_time('mysql');$id=(int)($d['id']??0);$name=sanitize_text_field((string)($d['name']??''));$slug=$this->uniqueSlug(sanitize_title((string)($d['slug']??$name)),$id);$photo=!empty($d['photo_id'])?(int)$d['photo_id']:null;$profile=wp_kses_post((string)($d['profile']??''));$status=in_array(($d['status']??'draft'),['draft','published'],true)?$d['status']:'draft';$order=max(0,(int)($d['display_order']??0));if($id){$old=(string)$wpdb->get_var($wpdb->prepare("SELECT slug FROM {$t} WHERE id=%d",$id));$wpdb->update($t,['name'=>$name,'slug'=>$slug,'photo_id'=>$photo,'profile'=>$profile,'status'=>$status,'display_order'=>$order,'updated_at'=>$now],['id'=>$id],['%s','%s','%d','%s','%s','%d','%s'],['%d']);if($old&&$old!==$slug)$wpdb->insert($wpdb->prefix.'stageart_plugin_member_slug_history',['member_id'=>$id,'slug'=>$old,'created_at'=>$now],['%d','%s','%s']);}else{$wpdb->insert($t,['name'=>$name,'slug'=>$slug,'photo_id'=>$photo,'profile'=>$profile,'status'=>$status,'display_order'=>$order,'created_at'=>$now,'updated_at'=>$now],['%s','%s','%d','%s','%s','%d','%s','%s']);$id=(int)$wpdb->insert_id;}$this->replaceRoles($id,(array)($d['roles']??[]));$this->replaceSocial($id,(array)($d['social']??[]));$this->replaceCustomValues($id,(array)($d['custom_fields']??[]));return $id;}
    public function setOrder(array $ids):void{global $wpdb;$t=$wpdb->prefix.'stageart_plugin_members';foreach(array_values(array_unique(array_map('intval',$ids))) as $n=>$id)$wpdb->update($t,['display_order'=>$n+1,'updated_at'=>current_time('mysql')],['id'=>$id],['%d','%s'],['%d']);}
    public function fields(bool $activeOnly=false):array{global $wpdb;$t=$wpdb->prefix.'stageart_plugin_member_fields';$w=$activeOnly?'WHERE is_active=1':'';return $wpdb->get_results("SELECT * FROM {$t} {$w} ORDER BY display_order ASC,id ASC",ARRAY_A)?:[];}
    public function saveField(array $d):int{global $wpdb;$t=$wpdb->prefix.'stageart_plugin_member_fields';$id=(int)($d['id']??0);$name=sanitize_text_field((string)($d['name']??''));$desc=sanitize_textarea_field((string)($d['description']??''));$now=current_time('mysql');if($id){$wpdb->update($t,['name'=>$name,'description'=>$desc,'updated_at'=>$now],['id'=>$id],['%s','%s','%s'],['%d']);return $id;}$key=$this->uniqueFieldKey(sanitize_key((string)($d['field_key']??$name)));$max=(int)$wpdb->get_var("SELECT COALESCE(MAX(display_order),0) FROM {$t}");$wpdb->insert($t,['field_key'=>$key,'name'=>$name,'description'=>$desc,'is_active'=>1,'display_order'=>$max+1,'created_at'=>$now,'updated_at'=>$now],['%s','%s','%s','%d','%d','%s','%s']);return (int)$wpdb->insert_id;}
    public function setFieldState(int $id,bool $active):void{global $wpdb;$wpdb->update($wpdb->prefix.'stageart_plugin_member_fields',['is_active'=>$active?1:0,'updated_at'=>current_time('mysql')],['id'=>$id],['%d','%s'],['%d']);}
    public function setFieldOrder(array $ids):void{global $wpdb;$t=$wpdb->prefix.'stageart_plugin_member_fields';foreach(array_values(array_unique(array_map('intval',$ids))) as $n=>$id)$wpdb->update($t,['display_order'=>$n+1,'updated_at'=>current_time('mysql')],['id'=>$id],['%d','%s'],['%d']);}
    private function roles(int $id):array{global $wpdb;return array_map('strval',$wpdb->get_col($wpdb->prepare("SELECT role_key FROM {$wpdb->prefix}stageart_plugin_member_roles WHERE member_id=%d",$id))?:[]);}
    private function social(int $id):array{global $wpdb;$rows=$wpdb->get_results($wpdb->prepare("SELECT platform,url FROM {$wpdb->prefix}stageart_plugin_member_social_links WHERE member_id=%d",$id),ARRAY_A)?:[];$o=[];foreach($rows as $r)$o[$r['platform']]=$r['url'];return $o;}
    private function customValues(int $id):array{global $wpdb;$rows=$wpdb->get_results($wpdb->prepare("SELECT field_id,value FROM {$wpdb->prefix}stageart_plugin_member_field_values WHERE member_id=%d",$id),ARRAY_A)?:[];$o=[];foreach($rows as $r){$o[(int)$r['field_id']]=$r['value'];}return $o;}
    private function replaceRoles(int $id,array $roles):void{global $wpdb;$t=$wpdb->prefix.'stageart_plugin_member_roles';$wpdb->delete($t,['member_id'=>$id],['%d']);foreach(array_unique($roles) as $r)if(isset(self::ROLES[$r]))$wpdb->insert($t,['member_id'=>$id,'role_key'=>$r],['%d','%s']);}
    private function replaceSocial(int $id,array $social):void{global $wpdb;$t=$wpdb->prefix.'stageart_plugin_member_social_links';$wpdb->delete($t,['member_id'=>$id],['%d']);$now=current_time('mysql');foreach(self::SOCIAL_PLATFORMS as $p=>$_){$url=!empty($social[$p])?esc_url_raw((string)$social[$p]):'';if($url)$wpdb->insert($t,['member_id'=>$id,'platform'=>$p,'url'=>$url,'created_at'=>$now,'updated_at'=>$now],['%d','%s','%s','%s','%s']);}}
    private function replaceCustomValues(int $id,array $values):void{global $wpdb;$t=$wpdb->prefix.'stageart_plugin_member_field_values';$now=current_time('mysql');foreach($this->fields(true) as $f){$fid=(int)$f['id'];if(!array_key_exists($fid,$values))continue;$v=sanitize_textarea_field((string)$values[$fid]);$existing=(int)$wpdb->get_var($wpdb->prepare("SELECT id FROM {$t} WHERE member_id=%d AND field_id=%d",$id,$fid));if($existing)$wpdb->update($t,['value'=>$v,'updated_at'=>$now],['id'=>$existing],['%s','%s'],['%d']);else$wpdb->insert($t,['member_id'=>$id,'field_id'=>$fid,'value'=>$v,'created_at'=>$now,'updated_at'=>$now],['%d','%d','%s','%s']);}}
    private function uniqueSlug(string $slug,int $ignore=0):string{global $wpdb;$members=$wpdb->prefix.'stageart_plugin_members';$history=$wpdb->prefix.'stageart_plugin_member_slug_history';$base=$slug?:'member';$c=$base;$i=2;while((int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$members} WHERE slug=%s AND id<>%d",$c,$ignore))||(int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$history} WHERE slug=%s",$c)))$c=$base.'-'.($i++);return $c;}
    private function uniqueFieldKey(string $key):string{global $wpdb;$t=$wpdb->prefix.'stageart_plugin_member_fields';$base=$key?:'field';$c=$base;$i=2;while((int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$t} WHERE field_key=%s",$c)))$c=$base.'-'.($i++);return $c;}
}
