<?php

declare(strict_types=1);
namespace StageArtPlugIn\Presentation\PublicSite;
use StageArtPlugIn\Domain\Production\ProductionRepository;
use StageArtPlugIn\Domain\Production\ProductionCreditRepository;
use StageArtPlugIn\Domain\Member\MemberRepository;
final class ProductionRouter{
 public function register():void{add_action('init',[$this,'rewrite']);add_filter('query_vars',[$this,'vars']);add_action('template_redirect',[$this,'render'],2);}
 public function rewrite():void{add_rewrite_rule('^production/([^/]+)/?$','index.php?stageart_production_slug=$matches[1]','top');}
 public function vars(array $v):array{$v[]='stageart_production_slug';return $v;}
 private function released($v):bool{if(!$v)return true;try{$n=new \DateTimeImmutable('now',new \DateTimeZone('UTC'));return $n>=new \DateTimeImmutable((string)$v,new \DateTimeZone('UTC'));}catch(\Throwable){return false;}}
 public function render():void{$slug=get_query_var('stageart_production_slug');if(!is_string($slug)||$slug==='')return;$q=new \WP_Query(['post_type'=>'stageart_production','name'=>$slug,'post_status'=>'publish','posts_per_page'=>1]);if(!$q->have_posts()){global $wp_query;$wp_query->set_404();status_header(404);$t=get_404_template();if($t)include $t;exit;}$p=$q->posts[0];$m=get_post_meta($p->ID);$g=fn($k,$d='')=>(string)($m[$k][0]??$d);$r=new ProductionRepository();$c=new ProductionCreditRepository();get_header();echo '<main class="stageart-production"><article><h1>'.esc_html($p->post_title).'</h1>';if($this->released($g('main_image_release'))&&$g('main_image_id'))echo wp_get_attachment_image((int)$g('main_image_id'),'large');if($this->released($g('summary_release'))&&$g('summary'))echo '<p>'.esc_html($g('summary')).'</p>';if($this->released($g('description_release'))&&$g('description'))echo '<section><h2>公演紹介</h2>'.wp_kses_post($g('description')).'</section>';if($this->released($g('schedule_release'))&&($g('schedule_start')||$g('schedule_end')))echo '<section><h2>公演日程</h2><p>'.esc_html($g('schedule_start')).($g('schedule_end')?' ～ '.esc_html($g('schedule_end')):'').'</p></section>';if($this->released($g('performance_release'))){$ps=$r->performances($p->ID);if($ps){echo '<section><h2>公演回</h2><table><tr><th>日付</th><th>開演</th><th>終演予定</th><th>公演回</th></tr>';foreach($ps as $x){$cell=$g('use_labels','1')==='1'?($g('label_display','symbol')==='both'&&$x['label_name']?$x['symbol'].' '.$x['label_name']:$x['symbol']):$g('performance_marker','●');echo '<tr><td>'.esc_html($x['performance_date']).'</td><td>'.esc_html(substr($x['start_time'],0,5)).'</td><td>'.esc_html($x['end_time']?substr($x['end_time'],0,5):'').'</td><td>'.esc_html($cell).'</td></tr>';}echo '</table>';if($g('legend','none')!=='none'&&$g('use_labels','1')==='1'){echo '<p>';foreach($r->labels($p->ID) as $l)echo esc_html($l['symbol'].' '.$l['name']).'　';echo '</p>'; }echo '</section>';}}
 if($this->released($g('venue_release'))&&$g('venue_name'))echo '<section><h2>会場</h2><p>'.esc_html($g('venue_name')).'</p>'.($this->released($g('venue_map_release'))&&$g('venue_map')?'<p><a href="'.esc_url($g('venue_map')).'" target="_blank" rel="noopener">Google Maps</a></p>':'').'</section>';
 foreach(['cast'=>'出演者','staff'=>'スタッフ'] as $kind=>$title){$release=$kind==='cast'?$g('cast_release'):$g('staff_release');if(!$this->released($release))continue;$rows=$r->participants($p->ID,$kind);if(!$rows)continue;echo '<section><h2>'.esc_html($title).'</h2><ul>';foreach($rows as $x){$n=esc_html($x['name']);if($x['member_id']){$mem=(new MemberRepository())->find((int)$x['member_id']);if($mem&&$mem['status']==='published')$n='<a href="'.esc_url(home_url('/member/'.rawurlencode($mem['slug']).'/')).'">'.$n.'</a>';}echo '<li>'.$n.($x['role']?'　'.esc_html($x['role']):'').'</li>';}echo '</ul></section>';}
 if($this->released($g('ticket_release'))){$ts=$r->tickets($p->ID);if($ts){echo '<section><h2>チケット料金</h2><ul>';foreach($ts as $x){$tax=$g('tax_display','included')==='included'?'（税込）':($g('tax_display')==='excluded'?'（税別）':'');echo '<li>'.esc_html($x['description']).'：'.number_format($x['amount']).'円'.esc_html($tax).'</li>';}echo '</ul>';if($g('ticket_comment'))echo wp_kses_post(wpautop($g('ticket_comment')));echo '</section>';}}
 foreach($c->sections($p->ID,true) as $s){if(!$s['items'])continue;echo '<section><h2>'.esc_html($s['name']).'</h2><ul>';foreach($s['items'] as $x)echo '<li>'.($x['url']?'<a href="'.esc_url($x['url']).'" target="_blank" rel="noopener">'.esc_html($x['name']).'</a>':esc_html($x['name'])).'</li>';echo '</ul></section>';}
 echo '</article></main>';get_footer();}
}
