<?php
declare(strict_types=1);
namespace StageArtPlugIn\Presentation\PublicSite;
use StageArtPlugIn\Domain\Survey\SurveyRepository;
final class SurveyRouter{
 private SurveyRepository $repo;public function __construct(){$this->repo=new SurveyRepository();}
 public function register():void{add_action('init',[$this,'rewrite']);add_filter('query_vars',[$this,'vars']);add_action('template_redirect',[$this,'render']);}
 public function rewrite():void{add_rewrite_rule('^production/([^/]+)/([^/]+)/?$','index.php?stageart_production_slug=$matches[1]&stageart_survey_slug=$matches[2]','top');}
 public function vars(array $vars):array{$vars[]='stageart_production_slug';$vars[]='stageart_survey_slug';return $vars;}
 public function render():void{$ps=(string)get_query_var('stageart_production_slug');$ss=(string)get_query_var('stageart_survey_slug');if($ps===''||$ss==='')return;$production=get_page_by_path($ps,OBJECT,'stageart_production');if(!$production||$production->post_status!=='publish')return;$survey=$this->repo->findByProduction((int)$production->ID);if(!$survey||(string)$survey['slug']!==$ss||(string)$survey['status']!=='publish')return;$questions=$this->repo->questions((int)$survey['id']);$performances=$this->repo->performancesForSurvey((int)$production->ID);if(isset($_POST['stageart_submit_survey'])){$this->submit($survey,$questions,$performances,$production);return;}get_header();echo '<main class="stageart-survey"><div class="stageart-survey-inner"><p><a href="'.esc_url(home_url('/production/'.$production->post_name.'/')).'">'.esc_html($production->post_title).'へ戻る</a></p><h1>'.esc_html($survey['title']).'</h1>';if(!empty($survey['description']))echo '<div>'.wp_kses_post($survey['description']).'</div>';if(!$questions)echo '<p>現在、アンケートの設問はありません。</p>';else{echo '<form method="post">';wp_nonce_field('stageart_submit_survey','stageart_survey_nonce');echo '<p><label>ご覧になった公演回 <select name="performance_id" required><option value="">選択してください</option>';foreach($performances as $p)echo '<option value="'.(int)$p['id'].'">'.esc_html($p['performance_date'].' '.substr((string)$p['start_time'],0,5)).'</option>';echo '</select></label></p>';foreach($questions as $q)$this->question($q);echo '<p><button type="submit" name="stageart_submit_survey" value="1">回答を送信</button></p></form>';}echo '</div></main>';get_footer();exit;}
 private function question(array $q):void{$name='q_'.(int)$q['id'];$req=!empty($q['is_required']);echo '<fieldset><legend>'.esc_html($q['label']).($req?' *':'').'</legend>';if(!empty($q['description']))echo '<p>'.esc_html($q['description']).'</p>';switch($q['type']){case'radio':foreach((array)$q['options'] as $o)echo '<label><input type="radio" name="'.esc_attr($name).'" value="'.esc_attr($o).'" '.($req?'required':'').'> '.esc_html($o).'</label><br>';break;case'checkbox':foreach((array)$q['options'] as $o)echo '<label><input type="checkbox" name="'.esc_attr($name).'[]" value="'.esc_attr($o).'"> '.esc_html($o).'</label><br>';break;case'select':echo '<select name="'.esc_attr($name).'" '.($req?'required':'').'><option value="">選択してください</option>';foreach((array)$q['options'] as $o)echo '<option value="'.esc_attr($o).'">'.esc_html($o).'</option>';echo '</select>';break;case'rating':echo '<select name="'.esc_attr($name).'" '.($req?'required':'').'><option value="">評価を選択</option>';for($n=1;$n<=5;$n++)echo '<option value="'.$n.'">'.$n.'</option>';echo '</select>';break;case'textarea':echo '<textarea name="'.esc_attr($name).'" rows="5" '.($req?'required':'').'></textarea>';break;default:echo '<input type="text" name="'.esc_attr($name).'" '.($req?'required':'').'>'; }echo '</fieldset>';}
 private function submit(array $survey,array $questions,array $performances,\WP_Post $production):void{if(!isset($_POST['stageart_survey_nonce'])||!wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['stageart_survey_nonce'])),'stageart_submit_survey'))wp_die('不正な送信です。');$performanceId=(int)($_POST['performance_id']??0);$valid=array_filter($performances,static fn($p)=>(int)$p['id']===$performanceId);if(!$valid)wp_die('公演回を選択してください。');$raw=wp_unslash($_POST);$answers=[];foreach($questions as $q){$key='q_'.(int)$q['id'];$value=$raw[$key]??'';if(is_array($value))$value=array_values(array_map('sanitize_text_field',$value));else $value=sanitize_textarea_field((string)$value);if(!empty($q['is_required'])&&($value===''||$value===[]))wp_die('必須項目に回答してください。');$answers[(string)$q['id']=$value;}$this->repo->saveResponse((int)$survey['id'],$performanceId,$answers);get_header();echo '<main class="stageart-survey"><div class="stageart-survey-inner"><h1>ご回答ありがとうございました</h1><p>アンケートを受け付けました。</p><p><a href="'.esc_url(home_url('/production/'.$production->post_name.'/')).'">公演ページへ戻る</a></p></div></main>';get_footer();exit;}
}
