<?php

declare(strict_types=1);
namespace StageArtPlugIn\Presentation\Admin;
use StageArtPlugIn\Domain\Production\ProductionRepository;
use StageArtPlugIn\Domain\Production\ProductionCreditRepository;
use StageArtPlugIn\Domain\Member\MemberRepository;

final class ProductionAdmin
{
    private ProductionRepository $repo; private ProductionCreditRepository $credits;
    public function __construct(){ $this->repo=new ProductionRepository();$this->credits=new ProductionCreditRepository(); }
    public function register():void{
        register_post_type('stageart_production',['labels'=>['name'=>'公演','singular_name'=>'公演','add_new'=>'公演を追加','edit_item'=>'公演を編集'],'public'=>false,'show_ui'=>true,'show_in_menu'=>false,'supports'=>['title'],'rewrite'=>false,'map_meta_cap'=>true]);
        add_submenu_page('stageart-plugin','公演','公演','manage_options','stageart-productions',[$this,'render']);
        add_action('admin_post_stageart_save_production',[$this,'save']);
        add_action('admin_enqueue_scripts',[$this,'assets']);
    }
    public function assets(string $hook):void{if(str_contains($hook,'stageart-productions'))wp_enqueue_media();}
    private function guard():void{if(!current_user_can('manage_options'))wp_die('権限がありません。');check_admin_referer('stageart_production_action');}
    private function utc(?string $v):?string{if(!$v)return null;$d=\DateTimeImmutable::createFromFormat('Y-m-d H:i',str_replace('T',' ',trim($v)),new \DateTimeZone('Asia/Tokyo'));return $d?$d->setTimezone(new \DateTimeZone('UTC'))->format('Y-m-d H:i:s'):null;}
    private function jst(?string $v):string{if(!$v)return '';try{$d=new \DateTimeImmutable($v,new \DateTimeZone('UTC'));return $d->setTimezone(new \DateTimeZone('Asia/Tokyo'))->format('Y-m-d\\TH:i');}catch(\Throwable){return '';}}
    public function render():void{
        $id=(int)($_GET['id']??0); if(isset($_GET['new']))$id=0; if($id){$p=get_post($id);if(!$p||$p->post_type!=='stageart_production')$id=0;}
        echo '<div class="wrap"><h1>公演</h1>';if(isset($_GET['saved']))echo '<div class="notice notice-success is-dismissible"><p>保存しました。</p></div>';
        if($id||isset($_GET['new'])){$this->form($id);echo '</div>';return;}
        echo '<p><a class="button button-primary" href="'.esc_url(admin_url('admin.php?page=stageart-productions&new=1')).'">＋ 公演を追加</a></p><table class="widefat striped"><thead><tr><th>公演名</th><th>状態</th><th>URL</th><th>操作</th></tr></thead><tbody>';
        $posts=get_posts(['post_type'=>'stageart_production','post_status'=>['publish','draft','private'],'numberposts'=>-1,'orderby'=>'date','order'=>'DESC']);foreach($posts as $p){echo '<tr><td><strong><a href="'.esc_url(admin_url('admin.php?page=stageart-productions&id='.$p->ID)).'">'.esc_html($p->post_title).'</a></strong></td><td>'.esc_html($p->post_status==='publish'?'公開':'下書き').'</td><td><code>'.esc_html(home_url('/production/'.($p->post_name?:$p->ID).'/')).'</code></td><td><a href="'.esc_url(admin_url('admin.php?page=stageart-productions&id='.$p->ID)).'">編集</a></td></tr>';}if(!$posts)echo '<tr><td colspan="4">公演はまだ登録されていません。</td></tr>';echo '</tbody></table></div>';
    }
    private function field(string $label,string $name,string $value,string $type='text',bool $required=false):void{echo '<tr><th><label>'.esc_html($label).($required?' *':'').'</label></th><td><input class="regular-text" type="'.esc_attr($type).'" name="'.esc_attr($name).'" value="'.esc_attr($value).'" '.($required?'required':'').' /></td></tr>';}
    private function form(int $id):void{
        $p=$id?get_post($id):null;$m=get_post_meta($id);$g=fn($k,$d='')=>(string)($m[$k][0]??$d);$members=(new MemberRepository())->all(false);$parts=$this->repo->participants($id);$cast=array_values(array_filter($parts,fn($x)=>$x['kind']==='cast'));$staff=array_values(array_filter($parts,fn($x)=>$x['kind']==='staff'));$labels=$this->repo->labels($id);$perfs=$this->repo->performances($id);$tickets=$this->repo->tickets($id);$sections=$this->credits->sections($id,false);
        echo '<form method="post" action="'.esc_url(admin_url('admin-post.php')).'">';wp_nonce_field('stageart_production_action');echo '<input type="hidden" name="action" value="stageart_save_production"><input type="hidden" name="id" value="'.(int)$id.'">';
        echo '<h2>基本情報</h2><table class="form-table">';$this->field('公演名','title',$p?$p->post_title:'','text',true);$this->field('Slug','slug',$p?$p->post_name:'');$this->field('メイン画像（メディアID）','main_image_id',$g('main_image_id'),'number');$this->field('メイン画像 情報解禁','main_image_release',$this->jst($g('main_image_release')),'datetime-local');$this->field('概要','summary',$g('summary'),'text');echo '<tr><th>概要 情報解禁</th><td><input type="datetime-local" name="summary_release" value="'.esc_attr($this->jst($g('summary_release'))).'" /></td></tr><tr><th>公演紹介</th><td><textarea class="large-text" rows="8" name="description">'.esc_textarea($g('description')).'</textarea></td></tr><tr><th>紹介 情報解禁</th><td><input type="datetime-local" name="description_release" value="'.esc_attr($this->jst($g('description_release'))).'" /></td></tr><tr><th>公開状態</th><td><select name="post_status"><option value="draft" '.selected($p->post_status??'draft','draft',false).'>下書き</option><option value="publish" '.selected($p->post_status??'draft','publish',false).'>公開</option></select></td></tr></table>';
        echo '<h2>公演日程</h2><table class="form-table">';$this->field('開始日','schedule_start',$g('schedule_start'),'date');$this->field('終了日','schedule_end',$g('schedule_end'),'date');echo '<tr><th>情報解禁</th><td><input type="datetime-local" name="schedule_release" value="'.esc_attr($this->jst($g('schedule_release'))).'" /></td></tr></table>';
        echo '<h2>公演回</h2><table class="form-table"><tr><th>情報解禁</th><td><input type="datetime-local" name="performance_release" value="'.esc_attr($this->jst($g('performance_release'))).'" /></td></tr><tr><th>ラベルを使用</th><td><label><input type="checkbox" name="use_labels" value="1" '.checked($g('use_labels','1'),'1',false).'> 使用する</label><p>公開表示形式は記号のみ／記号＋ラベル、凡例位置を下記で指定できます。</p></td></tr><tr><th>表示形式</th><td><select name="label_display"><option value="symbol" '.selected($g('label_display','symbol'),'symbol',false).'>記号のみ</option><option value="both" '.selected($g('label_display'),'both',false).'>記号＋ラベル</option></select><br>凡例 <select name="legend"><option value="none" '.selected($g('legend','none'),'none',false).'>表示しない</option><option value="above" '.selected($g('legend'),'above',false).'>上</option><option value="below" '.selected($g('legend'),'below',false).'>下</option></select><br>ラベル未使用時マーカー <input name="performance_marker" value="'.esc_attr($g('performance_marker','●')).'" maxlength="10" /></td></tr></table>';
        echo '<h3>公演回ラベル</h3><table class="widefat"><thead><tr><th>記号</th><th>ラベル</th></tr></thead><tbody>';foreach($labels as $i=>$l)echo '<tr><td><input name="labels['.$i.'][symbol]" value="'.esc_attr($l['symbol']).'"></td><td><input name="labels['.$i.'][name]" value="'.esc_attr($l['name']).'"></td></tr>';echo '<tr><td><input name="labels[new][symbol]"></td><td><input name="labels[new][name]"></td></tr></tbody></table><p class="description">空欄の行は保存時に無視します。</p>';
        echo '<h3>公演回</h3><table class="widefat"><thead><tr><th>開催日</th><th>開演</th><th>終演予定</th><th>ラベル</th></tr></thead><tbody>';foreach($perfs as $i=>$x){echo '<tr><td><input type="date" name="performances['.$i.'][date]" value="'.esc_attr($x['performance_date']).'"></td><td><input type="time" name="performances['.$i.'][start]" value="'.esc_attr(substr($x['start_time'],0,5)).'"></td><td><input type="time" name="performances['.$i.'][end]" value="'.esc_attr($x['end_time']?substr($x['end_time'],0,5):'').'"></td><td><select name="performances['.$i.'][label_id]"><option value="">なし</option>';foreach($labels as $l)echo '<option value="'.(int)$l['id'].'" '.selected((int)$x['label_id'],(int)$l['id'],false).'>'.esc_html($l['symbol'].' '.$l['name']).'</option>';echo '</select></td></tr>';}for($i=count($perfs);$i<count($perfs)+5;$i++)echo '<tr><td><input type="date" name="performances['.$i.'][date]"></td><td><input type="time" name="performances['.$i.'][start]"></td><td><input type="time" name="performances['.$i.'][end]"></td><td><select name="performances['.$i.'][label_id]"><option value="">なし</option>';foreach($labels as $l)echo '<option value="'.(int)$l['id'].'">'.esc_html($l['symbol'].' '.$l['name']).'</option>';echo '</select></td></tr>';echo '</tbody></table>';
        echo '<h2>会場</h2><table class="form-table">';$this->field('会場名','venue_name',$g('venue_name'));$this->field('会場 情報解禁','venue_release',$this->jst($g('venue_release')),'datetime-local');$this->field('Google Maps検索名/URL','venue_map',$g('venue_map'));$this->field('Google Maps 情報解禁','venue_map_release',$this->jst($g('venue_map_release')),'datetime-local');echo '</table>';
        $this->participantsForm('出演者',$cast,$members,'cast');$this->participantsForm('スタッフ',$staff,$members,'staff');
        echo '<h2>チケット料金</h2><table class="form-table"><tr><th>情報解禁</th><td><input type="datetime-local" name="ticket_release" value="'.esc_attr($this->jst($g('ticket_release'))).'" /></td></tr><tr><th>税表示</th><td><select name="tax_display"><option value="included" '.selected($g('tax_display','included'),'included',false).'>税込</option><option value="excluded" '.selected($g('tax_display'),'excluded',false).'>税別</option><option value="none" '.selected($g('tax_display'),'none',false).'>表示しない</option></select></td></tr></table><table class="widefat"><thead><tr><th>チケット種別</th><th>金額（円）</th><th>予約画面に表示</th></tr></thead><tbody>';foreach($tickets as $i=>$t)echo '<tr><td><input name="tickets['.$i.'][description]" value="'.esc_attr($t['description']).'"></td><td><input type="number" min="0" step="1" name="tickets['.$i.'][amount]" value="'.(int)$t['amount'].'"></td><td><input type="checkbox" name="tickets['.$i.'][show_on_reservation]" value="1" '.checked($t['show_on_reservation'],true,false).'></td></tr>';for($i=count($tickets);$i<count($tickets)+5;$i++)echo '<tr><td><input name="tickets['.$i.'][description]"></td><td><input type="number" min="0" step="1" name="tickets['.$i.'][amount]"></td><td><input type="checkbox" name="tickets['.$i.'][show_on_reservation]" value="1" checked></td></tr>';echo '</tbody></table><p>コメント</p><textarea class="large-text" rows="5" name="ticket_comment">'.esc_textarea($g('ticket_comment')).'</textarea>';
        echo '<h2>公演クレジット</h2>';foreach($sections as $i=>$s){echo '<div class="card"><h3>区分 '.($i+1).'</h3><input name="credits['.$i.'][name]" value="'.esc_attr($s['name']).'" placeholder="区分名"><input type="datetime-local" name="credits['.$i.'][release_at]" value="'.esc_attr($this->jst($s['release_at'])).'"><input type="hidden" name="credits['.$i.'][id]" value="'.(int)$s['id'].'">';foreach($s['items'] as $j=>$it)echo '<p><input name="credits['.$i.'][items]['.$j.'][name]" value="'.esc_attr($it['name']).'" placeholder="名称"> <input type="url" name="credits['.$i.'][items]['.$j.'][url]" value="'.esc_attr($it['url']??'').'" placeholder="リンク"></p>';echo '<p><input name="credits['.$i.'][items][new][name]" placeholder="項目名"> <input type="url" name="credits['.$i.'][items][new][url]" placeholder="リンク"></p></div>';}echo '<div class="card"><h3>区分を追加</h3><input name="new_credit[name]" placeholder="区分名"><input type="datetime-local" name="new_credit[release_at]"><p><input name="new_credit[items][0][name]" placeholder="項目名"> <input type="url" name="new_credit[items][0][url]" placeholder="リンク"></p></div>';
        echo '<p><button class="button button-primary button-large" type="submit">保存</button> <a class="button" href="'.esc_url(admin_url('admin.php?page=stageart-productions')).'">キャンセル</a></p></form>';
    }
    private function participantsForm(string $title,array $rows,array $members,string $kind):void{echo '<h2>'.esc_html($title).'</h2><table class="widefat"><thead><tr><th>表示名</th><th>役割</th><th>メンバー</th><th>AuthCoreユーザーID</th></tr></thead><tbody>';foreach($rows as $i=>$r){$this->participantRow($i,$r,$members,$kind);}for($i=count($rows);$i<count($rows)+5;$i++)$this->participantRow($i,[], $members,$kind);echo '</tbody></table>';}
    private function participantRow(int $i,array $r,array $members,string $kind):void{echo '<tr><td><input name="participants['.$kind.']['.$i.'][name]" value="'.esc_attr($r['name']??'').'"></td><td><input name="participants['.$kind.']['.$i.'][role]" value="'.esc_attr($r['role']??'').'"></td><td><select name="participants['.$kind.']['.$i.'][member_id]"><option value="">なし</option>';foreach($members as $m){$sel=((int)($r['member_id']??0)===(int)$m['id']);echo '<option value="'.(int)$m['id'].'" '.selected($sel,true,false).'>'.esc_html($m['name']).'</option>';}echo '</select></td><td><input type="number" min="0" name="participants['.$kind.']['.$i.'][auth_user_id]" value="'.esc_attr($r['auth_user_id']??'').'"></td></tr>';}
    public function save():void{
        $this->guard();$id=(int)($_POST['id']??0);$title=sanitize_text_field(wp_unslash($_POST['title']??''));if($title==='')wp_die('公演名は必須です。');$slug=sanitize_title(wp_unslash($_POST['slug']??''));$args=['post_type'=>'stageart_production','post_title'=>$title,'post_status'=>in_array($_POST['post_status']??'draft',['draft','publish'],true)?$_POST['post_status']:'draft','post_name'=>$slug];if($id){$args['ID']=$id;$id=wp_update_post(wp_slash($args),true);}else{$id=wp_insert_post(wp_slash($args),true);}if(is_wp_error($id))wp_die(esc_html($id->get_error_message()));
        $text=['summary','description','schedule_start','schedule_end','venue_name','venue_map','performance_marker','ticket_comment'];foreach($text as $k){$v=wp_unslash($_POST[$k]??'');if($k==='description')$v=wp_kses_post($v);else $v=sanitize_text_field($v);update_post_meta($id,$k,$v);}foreach(['main_image_id'] as $k)update_post_meta($id,$k,max(0,(int)($_POST[$k]??0)));foreach(['main_image_release','summary_release','description_release','schedule_release','performance_release','venue_release','venue_map_release','ticket_release'] as $k){$v=$this->utc(sanitize_text_field(wp_unslash($_POST[$k]??'')));if($v)update_post_meta($id,$k,$v);else delete_post_meta($id,$k);}foreach(['use_labels','label_display','legend','tax_display'] as $k){$v=sanitize_key(wp_unslash($_POST[$k]??''));if($k==='use_labels')$v=isset($_POST[$k])?'1':'0';update_post_meta($id,$k,$v);}update_post_meta($id,'main_image_release',$this->utc(sanitize_text_field(wp_unslash($_POST['main_image_release']??''))));
        $this->repo->saveLabels($id,(array)($_POST['labels']??[]));$this->repo->savePerformances($id,(array)($_POST['performances']??[]));$this->repo->saveParticipants($id,'cast',(array)($_POST['participants']['cast']??[]));$this->repo->saveParticipants($id,'staff',(array)($_POST['participants']['staff']??[]));$this->repo->saveTickets($id,(array)($_POST['tickets']??[]));
        $sections=(array)($_POST['credits']??[]);foreach($sections as $s){$name=sanitize_text_field(wp_unslash($s['name']??''));if($name==='')continue;$sid=(int)($s['id']??0);$release=$this->utc(sanitize_text_field(wp_unslash($s['release_at']??'')));if($sid)$this->credits->updateSection($sid,$name,$release,(int)($s['display_order']??0));else$sid=$this->credits->createSection($id,$name,$release,9999);$items=[];foreach((array)($s['items']??[]) as $it){$n=sanitize_text_field(wp_unslash($it['name']??''));if($n!=='')$items[]=['name'=>$n,'url'=>esc_url_raw(wp_unslash($it['url']??''))];}$existing=$this->credits->items($sid);$this->credits->deleteSection($sid);$sid=$this->credits->createSection($id,$name,$release,(int)($s['display_order']??0));foreach($items as $j=>$it)$this->credits->createItem($sid,$it['name'],$it['url'],$j);}
        $nc=(array)($_POST['new_credit']??[]);$nn=sanitize_text_field(wp_unslash($nc['name']??''));if($nn!==''){$sid=$this->credits->createSection($id,$nn,$this->utc(sanitize_text_field(wp_unslash($nc['release_at']??''))),9999);foreach((array)($nc['items']??[]) as $j=>$it){$n=sanitize_text_field(wp_unslash($it['name']??''));if($n!=='')$this->credits->createItem($sid,$n,esc_url_raw(wp_unslash($it['url']??'')),$j);}}
        wp_safe_redirect(admin_url('admin.php?page=stageart-productions&id='.$id.'&saved=1'));exit;
    }
}
