<?php
declare(strict_types=1);
namespace StageArtPlugIn\Presentation\Admin;
use StageArtPlugIn\Domain\Survey\SurveyRepository;
final class SurveyAdmin{
 private SurveyRepository $repo;public function __construct(){$this->repo=new SurveyRepository();}
 public function register():void{add_submenu_page('stageart-plugin','アンケート','アンケート','manage_options','stageart-surveys',[$this,'render']);add_action('admin_post_stageart_save_survey',[$this,'save']);}
 public function render():void{if(!current_user_can('manage_options'))wp_die('権限がありません。');$pid=(int)($_GET['production_id']??0);$p=$pid?get_post($pid):null;if(!$p||$p->post_type!=='stageart_production'){echo '<div class="wrap"><h1>アンケート</h1><p>対象の公演が指定されていません。</p></div>';return;}$s=$this->repo->findByProduction($pid);$qs=$s?$this->repo->questions((int)$s['id']):[];echo '<div class="wrap"><h1>公演アンケート</h1><p><strong>公演：</strong>'.esc_html($p->post_title).'</p>';if($s)echo '<p><a class="button" href="'.esc_url(admin_url('admin.php?page=stageart-survey-results&survey_id='.(int)$s['id'])).'">アンケート結果を見る</a></p>';echo '<form method="post" action="'.esc_url(admin_url('admin-post.php')).'">';wp_nonce_field('stageart_survey_action');echo '<input type="hidden" name="action" value="stageart_save_survey"><input type="hidden" name="production_id" value="'.$pid.'"><table class="form-table"><tr><th>タイトル</th><td><input class="regular-text" name="title" value="'.esc_attr($s['title']??'アンケート').'"></td></tr><tr><th>説明</th><td><textarea class="large-text" rows="4" name="description">'.esc_textarea($s['description']??'').'</textarea></td></tr><tr><th>公開URL</th><td><code>'.esc_html(home_url('/production/'.($p->post_name?:$pid).'/questionnaire/')).'</code></td></tr><tr><th>公開状態</th><td><select name="status"><option value="publish" '.selected($s['status']??'publish','publish',false).'>公開</option><option value="draft" '.selected($s['status']??'publish','draft',false).'>下書き</option></select></td></tr></table><h2>設問</h2><table class="widefat" id="sa-survey-questions"><thead><tr><th>形式</th><th>質問</th><th>説明</th><th>必須</th><th>選択肢</th><th></th></tr></thead><tbody>';foreach($qs as $i=>$q)$this->row($i,$q);echo '</tbody></table><p><button type="button" class="button" id="sa-add-survey-question">＋ 設問を追加</button></p><p><button class="button button-primary" type="submit">保存</button></p></form></div>';$this->script();}
 private function row(int $i,array $q):void{$o=(array)($q['options']??[]);echo '<tr><td><input type="hidden" name="questions['.$i.'][id]" value="'.(int)($q['id']??0).'"><select name="questions['.$i.'][type]"><option value="text" '.selected($q['type']??'','text',false).'>短文</option><option value="textarea" '.selected($q['type']??'','textarea',false).'>長文</option><option value="radio" '.selected($q['type']??'','radio',false).'>ラジオ</option><option value="checkbox" '.selected($q['type']??'','checkbox',false).'>複数選択</option><option value="select" '.selected($q['type']??'','select',false).'>プルダウン</option><option value="rating" '.selected($q['type']??'','rating',false).'>5段階評価</option></select></td><td><input class="regular-text" name="questions['.$i.'][label]" value="'.esc_attr($q['label']??'').'" required></td><td><input class="regular-text" name="questions['.$i.'][description]" value="'.esc_attr($q['description']??'').'"></td><td><input type="checkbox" name="questions['.$i.'][is_required]" value="1" '.checked(!empty($q['is_required']),true,false).'></td><td><textarea name="questions['.$i.'][options]" rows="3" placeholder="1行1選択肢">'.esc_textarea(implode("\n",array_map('strval',$o))).'</textarea></td><td><button type="button" class="button-link-delete sa-survey-remove">削除</button></td></tr>';}
 private function save():void{if(!current_user_can('manage_options'))wp_die('権限がありません。');check_admin_referer('stageart_survey_action');$pid=(int)($_POST['production_id']??0);$qs=[];foreach((array)($_POST['questions']??[]) as $q){if(!is_array($q))continue;$qs[]=['id'=>(int)($q['id']??0),'type'=>sanitize_key((string)($q['type']??'textarea')),'label'=>(string)($q['label']??''),'description'=>(string)($q['description']??''),'is_required'=>!empty($q['is_required']),'options'=>preg_split('/\r\n|\r|\n/',(string)($q['options']??''))?:[]];}$this->repo->save($pid,['title'=>(string)($_POST['title']??'アンケート'),'description'=>(string)($_POST['description']??''),'slug'=>'questionnaire','status'=>sanitize_key((string)($_POST['status']??'publish'))],$qs);wp_safe_redirect(admin_url('admin.php?page=stageart-surveys&production_id='.$pid.'&saved=1'));exit;}
 private function script():void{echo '<script>(function(){const t=document.querySelector("#sa-survey-questions tbody"),a=document.querySelector("#sa-add-survey-question");if(!t||!a)return;a.onclick=()=>{const i=t.children.length;t.insertAdjacentHTML("beforeend",`<tr><td><input type="hidden" name="questions[${i}][id]" value="0"><select name="questions[${i}][type]"><option value="text">短文</option><option value="textarea" selected>長文</option><option value="radio">ラジオ</option><option value="checkbox">複数選択</option><option value="select">プルダウン</option><option value="rating">5段階評価</option></select></td><td><input class="regular-text" name="questions[${i}][label]" required></td><td><input class="regular-text" name="questions[${i}][description]"></td><td><input type="checkbox" name="questions[${i}][is_required]" value="1"></td><td><textarea name="questions[${i}][options]" rows="3" placeholder="1行1選択肢"></textarea></td><td><button type="button" class="button-link-delete sa-survey-remove">削除</button></td></tr>`)};t.onclick=e=>{if(e.target.classList.contains("sa-survey-remove"))e.target.closest("tr").remove()}})();</script>';}}
