<?php

declare(strict_types=1);
namespace StageArtPlugIn\Presentation\Admin;
use StageArtPlugIn\Domain\Survey\SurveyRepository;
final class SurveyAdmin{
 private SurveyRepository $repo;
 public function __construct(){ $this->repo=new SurveyRepository(); }
 public function register():void{add_submenu_page('stageart-plugin','アンケート','アンケート','manage_options','stageart-surveys',[$this,'render']);add_action('admin_post_stageart_save_survey',[$this,'save']);}
 public function render():void{
  if(!current_user_can('manage_options'))wp_die('権限がありません。');
  $productionId=(int)($_GET['production_id']??0);$production=$productionId?get_post($productionId):null;
  if(!$production||$production->post_type!=='stageart_production'){echo '<div class="wrap"><h1>アンケート</h1><p>対象の公演が指定されていません。</p></div>';return;}
  $survey=$this->repo->findByProduction($productionId);$questions=$survey?$this->repo->questions((int)$survey['id']):[];$release=$survey['release_at']??'';$releaseJst='';
  if($release){try{$releaseJst=(new \DateTimeImmutable($release,new \DateTimeZone('UTC')))->setTimezone(new \DateTimeZone('Asia/Tokyo'))->format('Y-m-d\\TH:i');}catch(\Throwable){}}
  echo '<div class="wrap"><h1>公演アンケート</h1><p><strong>公演：</strong>'.esc_html($production->post_title).'</p>';if(isset($_GET['saved']))echo '<div class="notice notice-success is-dismissible"><p>アンケートを保存しました。</p></div>';
  echo '<form method="post" action="'.esc_url(admin_url('admin-post.php')).'">';wp_nonce_field('stageart_survey_action');echo '<input type="hidden" name="action" value="stageart_save_survey"><input type="hidden" name="production_id" value="'.(int)$productionId.'">';
  echo '<table class="form-table"><tr><th>タイトル</th><td><input class="regular-text" name="title" value="'.esc_attr($survey['title']??'アンケート').'"></td></tr><tr><th>説明</th><td><textarea class="large-text" rows="4" name="description">'.esc_textarea($survey['description']??'').'</textarea></td></tr><tr><th>Slug</th><td><input class="regular-text" name="slug" value="'.esc_attr($survey['slug']??'questionnaire').'"><p class="description">公開URLは /production/'.esc_html($production->post_name?:$productionId).'/questionnaire/ を基本とします。</p></td></tr><tr><th>情報解禁</th><td><input type="datetime-local" name="release_at" value="'.esc_attr($releaseJst).'"><p class="description">空欄の場合は常時公開。</p></td></tr><tr><th>状態</th><td><select name="status"><option value="draft" '.selected($survey['status']??'draft','draft',false).'>下書き</option><option value="publish" '.selected($survey['status']??'draft','publish',false).'>公開</option></select></td></tr></table>';
  echo '<h2>設問</h2><table class="widefat" id="sa-survey-questions"><thead><tr><th>形式</th><th>質問</th><th>説明</th><th>必須</th><th>選択肢</th><th></th></tr></thead><tbody>';foreach($questions as $i=>$q)$this->questionRow($i,$q);echo '</tbody></table><p><button type="button" class="button" id="sa-add-survey-question">＋ 設問を追加</button></p>';
  echo '<p><button class="button button-primary button-large" type="submit">保存</button> <a class="button" href="'.esc_url(admin_url('admin.php?page=stageart-productions&id='.$productionId)).'">公演へ戻る</a></p></form></div>';$this->script();
 }
 private function questionRow(int $i,array $q):void{$o=(array)($q['options']??[]);echo '<tr class="sa-survey-question"><td><input type="hidden" name="questions['.$i.'][id]" value="'.(int)($q['id']??0).'"><select name="questions['.$i.'][type]"><option value="text" '.selected($q['type']??'','text',false).'>短文</option><option value="textarea" '.selected($q['type']??'','textarea',false).'>長文</option><option value="radio" '.selected($q['type']??'','radio',false).'>ラジオ</option><option value="checkbox" '.selected($q['type']??'','checkbox',false).'>複数選択</option><option value="select" '.selected($q['type']??'','select',false).'>プルダウン</option><option value="rating" '.selected($q['type']??'','rating',false).'>5段階評価</option></select></td><td><input class="regular-text" name="questions['.$i.'][label]" value="'.esc_attr($q['label']??'').'" required></td><td><input class="regular-text" name="questions['.$i.'][description]" value="'.esc_attr($q['description']??'').'" /></td><td><label><input type="checkbox" name="questions['.$i.'][is_required]" value="1" '.checked(!empty($q['is_required']),true,false).'> 必須</label></td><td><textarea name="questions['.$i.'][options]" rows="3" placeholder="1行1選択肢">'.esc_textarea(implode("\n",array_map('strval',$o))).'</textarea></td><td><button type="button" class="button-link-delete sa-survey-remove">削除</button></td></tr>';}
 private function save():void{
  if(!current_user_can('manage_options'))wp_die('権限がありません。');check_admin_referer('stageart_survey_action');$productionId=(int)($_POST['production_id']??0);$release=trim((string)($_POST['release_at']??''));$releaseUtc=null;
  if($release!==''){ $normalized=str_replace('T',' ',$release);$d=\DateTimeImmutable::createFromFormat('Y-m-d H:i',$normalized,new \DateTimeZone('Asia/Tokyo'));if(!$d||$d->format('Y-m-d H:i')!==$normalized)wp_die('情報解禁日時が正しくありません。','アンケート入力エラー',['response'=>400]);$releaseUtc=$d->setTimezone(new \DateTimeZone('UTC'))->format('Y-m-d H:i:s'); }
  $questions=[];foreach((array)($_POST['questions']??[]) as $q){if(!is_array($q))continue;$questions[]=['id'=>(int)($q['id']??0),'type'=>sanitize_key((string)($q['type']??'textarea')),'label'=>(string)($q['label']??''),'description'=>(string)($q['description']??''),'is_required'=>!empty($q['is_required']),'options'=>preg_split('/\r\n|\r|\n/',(string)($q['options']??''))?:[]];}
  $this->repo->save($productionId,['title'=>(string)($_POST['title']??'アンケート'),'description'=>(string)($_POST['description']??''),'slug'=>sanitize_title((string)($_POST['slug']??'questionnaire'))?:'questionnaire','release_at'=>$releaseUtc,'status'=>sanitize_key((string)($_POST['status']??'draft'))],$questions);
  wp_safe_redirect(admin_url('admin.php?page=stageart-surveys&production_id='.$productionId.'&saved=1'));exit;
 }
 private function script():void{echo '<script>(function(){const t=document.querySelector("#sa-survey-questions tbody"),a=document.querySelector("#sa-add-survey-question");if(!t||!a)return;function row(i){return `<tr class="sa-survey-question"><td><input type="hidden" name="questions[${i}][id]" value="0"><select name="questions[${i}][type]"><option value="text">短文</option><option value="textarea" selected>長文</option><option value="radio">ラジオ</option><option value="checkbox">複数選択</option><option value="select">プルダウン</option><option value="rating">5段階評価</option></select></td><td><input class="regular-text" name="questions[${i}][label]" required></td><td><input class="regular-text" name="questions[${i}][description]"></td><td><label><input type="checkbox" name="questions[${i}][is_required]" value="1"> 必須</label></td><td><textarea name="questions[${i}][options]" rows="3" placeholder="1行1選択肢"></textarea></td><td><button type="button" class="button-link-delete sa-survey-remove">削除</button></td></tr>`}function reindex(){t.querySelectorAll("tr").forEach((tr,i)=>tr.querySelectorAll("[name]").forEach(e=>e.name=e.name.replace(/questions\\[\\d+\\]/,`questions[${i}]`)))}a.addEventListener("click",()=>t.insertAdjacentHTML("beforeend",row(t.children.length)));t.addEventListener("click",e=>{if(e.target.classList.contains("sa-survey-remove")){e.target.closest("tr").remove();reindex()}});})();</script>';}
}
