<?php

declare(strict_types=1);
namespace StageArtPlugIn\Domain\Survey;
final class SurveyRepository{
 private \wpdb $db;private string $surveys;private string $questions;private string $responses;
 public function __construct(?\wpdb $db=null){global $wpdb;$this->db=$db??$wpdb;$p=$this->db->prefix;$this->surveys=$p.'stageart_plugin_production_surveys';$this->questions=$p.'stageart_plugin_production_survey_questions';$this->responses=$p.'stageart_plugin_production_survey_responses';}
 public function findByProduction(int $productionId):?array{$r=$this->db->get_row($this->db->prepare("SELECT * FROM {$this->surveys} WHERE production_id=%d LIMIT 1",$productionId),ARRAY_A);return $r?:null;}
 public function questions(int $surveyId):array{$r=$this->db->get_results($this->db->prepare("SELECT * FROM {$this->questions} WHERE survey_id=%d ORDER BY display_order,id",$surveyId),ARRAY_A)?:[];foreach($r as &$x){$x['id']=(int)$x['id'];$x['survey_id']=(int)$x['survey_id'];$x['is_required']=(bool)$x['is_required'];$o=json_decode((string)($x['options_json']??''),true);$x['options']=is_array($o)?$o:[];unset($x['options_json']);}return $r;}
 public function performancesForSurvey(int $productionId):array{$p=$this->db->prefix.'stageart_plugin_production_performances';return $this->db->get_results($this->db->prepare("SELECT id,performance_date,start_time,end_time FROM {$p} WHERE production_id=%d ORDER BY performance_date,start_time,id",$productionId),ARRAY_A)?:[];}
 public function save(int $productionId,array $data,array $questions):int{$now=gmdate('Y-m-d H:i:s');$existing=$this->findByProduction($productionId);$payload=['production_id'=>$productionId,'title'=>sanitize_text_field((string)($data['title']??'アンケート')),'description'=>wp_kses_post((string)($data['description']??'')),'slug'=>sanitize_title((string)($data['slug']??'questionnaire'))?:'questionnaire','status'=>in_array(($data['status']??'publish'),['draft','publish'],true)?$data['status']:'publish','updated_at'=>$now];if($existing){$this->db->update($this->surveys,$payload,['id'=>(int)$existing['id']]);$surveyId=(int)$existing['id'];}else{$payload['created_at']=$now;$this->db->insert($this->surveys,$payload);$surveyId=(int)$this->db->insert_id;}$old=$this->questions($surveyId);$keep=[];foreach(array_values($questions) as $i=>$q){if(!is_array($q))continue;$label=trim((string)($q['label']??''));if($label==='')continue;$qid=(int)($q['id']??0);$type=sanitize_key((string)($q['type']??'textarea'));$allowed=['text','textarea','radio','checkbox','select','rating'];if(!in_array($type,$allowed,true))$type='textarea';$opts=array_values(array_filter(array_map(static fn($v)=>sanitize_text_field((string)$v),(array)($q['options']??[])),static fn($v)=>$v!==''));$row=['survey_id'=>$surveyId,'type'=>$type,'label'=>sanitize_text_field($label),'description'=>sanitize_textarea_field((string)($q['description']??'')),'is_required'=>!empty($q['is_required'])?1:0,'display_order'=>$i,'options_json'=>wp_json_encode($opts,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),'updated_at'=>$now];if($qid>0)$this->db->update($this->questions,$row,['id'=>$qid,'survey_id'=>$surveyId]);else{$row['created_at']=$now;$this->db->insert($this->questions,$row);$qid=(int)$this->db->insert_id;}$keep[]=$qid;}foreach($old as $x)if(!in_array((int)$x['id'],$keep,true))$this->db->delete($this->questions,['id'=>(int)$x['id'],'survey_id'=>$surveyId]);return $surveyId;}
 public function saveResponse(int $surveyId,?int $performanceId,array $answers):int{$this->db->insert($this->responses,['survey_id'=>$surveyId,'performance_id'=>$performanceId,'submitted_at'=>gmdate('Y-m-d H:i:s'),'answers_json'=>wp_json_encode($answers,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)]);return (int)$this->db->insert_id;}
 public function responses(int $surveyId):array{$r=$this->db->get_results($this->db->prepare("SELECT * FROM {$this->responses} WHERE survey_id=%d ORDER BY submitted_at,id",$surveyId),ARRAY_A)?:[];foreach($r as &$x){$x['id']=(int)$x['id'];$x['performance_id']=$x['performance_id']!==null?(int)$x['performance_id']:null;$a=json_decode((string)$x['answers_json'],true);$x['answers']=is_array($a)?$a:[];unset($x['answers_json']);}return $r;}
 public function responseCount(int $surveyId):int{return count($this->responses($surveyId));}
}
